import os

TRACING_QUEUE_HOST = os.getenv('TRACING_QUEUE_HOST')
TRACING_QUEUE_USER = os.getenv('TRACING_QUEUE_USER')
TRACING_QUEUE_PASSWORD = os.getenv('TRACING_QUEUE_PASSWORD')
TRACING_ENABLED = TRACING_QUEUE_HOST and TRACING_QUEUE_USER and TRACING_QUEUE_PASSWORD
